server {
    listen 80 default_server;
    seerver_name _;
    root /var/www/docs2;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location ~* \.(js|css|png|jpeg|gif|svg|ico|webp)$ {
        try_files $uri =404;
    }
}
